### ISSUE TITLE
Add more info for huey

### ISSUE THREAD

**Issue by spapas** [boxine/django-huey-monitor#119]
Hello, would it be possible to add a view to this package that would display info about huey ?

Like connection, queue size, schedule size etc. Unless there's a way to see that info and I've missed it....

**Comment by jedie** [comment]
Geat idea. But how to collect these information?

Recently i add a small info on the task change list: 

![grafik](https://github.com/boxine/django-huey-monitor/assets/71315/6d0c899a-bacd-416a-85b8-7a99d52e03e3)

see: https://github.com/boxine/django-huey-monitor/pull/124

**Comment by spapas** [comment]
This should be fine for now, thank you!
