### ISSUE TITLE
run migrate after installing

### ISSUE THREAD

**Issue by BSVogler** [boxine/django-huey-monitor#16]
Hey,
I am currently testing huey with this monitor.

The QuickStart guide should contain that after installing it needs a `python manage.py migrate`.
Without it you will be greeted with an error message in the Django admin interface.

**Comment by jedie** [comment]
Hm. This is not needed if you use **./manage.sh run_testserver** This is a own manage command that will do all needed steps.

See: https://github.com/boxine/django-huey-monitor/blob/9f0f16a83315ab9763c93c7617d48f24018ccf2c/huey_monitor_tests/test_app/management/commands/run_testserver.py#L29-L41
