### ISSUE TITLE
'humanize_time' is not a registered tag library. 

### ISSUE THREAD

**Issue by BSVogler** [boxine/django-huey-monitor#21]
When clicking on a task-name this url is linked `/admin/huey_monitor/taskmodel/<taskid>/change/`. I then get the following error message.

```
'humanize_time' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
debugger_tags
guardian_tags
highlighting
i18n
import_export_tags
indent_text
l10n
log
rest_framework
static
syntax_color
tz
widont
```

**Comment by shsdev** [comment]
Same issue (django==3.1.7, django-huey-monitor==0.3.0, huey==2.3.1)

**Comment by jedie** [comment]
humanize_time comes from our "bx_py_utils": https://github.com/boxine/bx_py_utils/blob/master/bx_py_utils/templatetags/humanize_time.py

So the solution is to add "bx_py_utils" into **INSTALLED_APPS**

Maybe i add a check that display a hint to this.
