### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by BSVogler** [boxine/django-huey-monitor#47]
Thank you again for this lib :)

I would like to see this fix soon be integrated.
https://github.com/boxine/django-huey-monitor/pull/45

Could you please provide a new release or are you waiting for the completion of a new feature first?

**Comment by jedie** [comment]
Release will comming soon.

**Comment by jedie** [comment]
https://pypi.org/project/django-huey-monitor/0.4.2/ ist out
