### ISSUE TITLE
No feedback on PR throughput formating for rate<1 #48 for one month

### ISSUE THREAD

**Issue by formacube** [boxine/django-huey-monitor#49]
could you please give feedback and / or integrate PR #48 "throughput formating for rate<1" ?
It is availlable for one month already and there was not even a feedback even if it is quite straightforward.

Thanks in advance

**Comment by jedie** [comment]
Sorry for late response... We are all very busy ;)

Look at: https://github.com/boxine/django-huey-monitor/pull/48#issuecomment-959186166
