### ISSUE TITLE
[Question] Does this mean, dhm use the chosen database as the result storage and redis as the broker/queue?

### ISSUE THREAD

**Issue by simkimsia** [boxine/django-huey-monitor#52]
I use celery with django. want to come over to huey.

in celery, it separates broker/queue from result storage.

so by using django-huey-monitor (dhm) are you making huey use the database purely for result storage? and leave redis to handle the broker/queue?

**Comment by jedie** [comment]
No. It leaves the result storage up to huey.

**Comment by simkimsia** [comment]
> No. It leaves the result storage up to huey.

Thank you, Jens.

Just one last clarification

does this diagram capture well the whole flow including dhm?

![hueyv2 dhm logical](https://user-images.githubusercontent.com/245021/143182561-36ccdad0-ca3a-42a7-a637-0a06b900f724.png)

**Comment by jedie** [comment]
Yes, think it goes into the right destination ;)
