### ISSUE TITLE
Issue with ManifestStaticFilesStorage due to TaskModelAdmin referencing non-existent CSS file

### ISSUE THREAD

**Issue by henribru** [boxine/django-huey-monitor#55]
`TaskModelAdmin` references a CSS file called `huey_monitor.css`. This file doesn't actually exist, which causes problems if you're using Django's `ManifestStaticFilesStorage` or something inheriting from it like Whitenoise's `CompressedManifestStaticFilesStorage`. Specifically you end up with a ValueError and a 500 when navigating to the admin task list in production, unless you tweak the [manifest_strict](https://docs.djangoproject.com/en/3.2/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage.manifest_strict) setting. I'm not sure if this CSS thing is leftover from something or if it's meant to be an optional file that can be added by users of the library to customize how the Huey admin looks. In the former case, could we remove it so that we don't have to disable `manifest_strict`? In the latter case, is disabling `manifest_strict` the intended workaround for this issue?

**Comment by henribru** [comment]
Actually it turns out disabling `manifest_strict` doesn't fix this issue, at least not when using Whitenoise. You end up with another `ValueError`, "The file 'huey_monitor.css' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f47401bfd60>."

**Comment by jedie** [comment]
Hm. I didn't understand the real problem... Maybe you missed to run `collectstatic` ?!?

`huey_monitor.css` is a part of `huey_monitor.admin.TaskModelAdmin.Meta.css`, so that `collectstatic` will copy this file to the right place... What did i miss here?!?

**Comment by henribru** [comment]
I am running `collectstatic`, but that's not copying a `huey_monitor.css` to `./staticfiles/css`. There doesn't seem to be a `huey_monitor.css` file in this repository for it to copy?

**Comment by jedie** [comment]
Whoops. I understand now. Fixed by #55
New release is coming soon today ;)

**Comment by henribru** [comment]
Thanks :+1:
