### ISSUE TITLE
Reviewed PR waiting for merge for 1 month now

### ISSUE THREAD

**Issue by formacube** [boxine/django-huey-monitor#56]
Hi, could you proceed with the merge of https://github.com/boxine/django-huey-monitor/pull/44 ?

One month has passed since linting preferences have been adapted according to your preferences

Thanks in advance

**Comment by formacube** [comment]
I corrected 2 extra whitespaces which were " failing" !!!!!!!!!!!!!!! the tests (again ?)

I don't know exactly what is triggering the checking workflows.
I just have no idea what I'm doing, when I have to do what to get the things moving. I would appreciate a little bit of direction.
I have removed few whitespaces and added one linefeed since end of september ...

so I'm starting  to be a bit fedup

**Comment by jedie** [comment]
Just run `make fix-code-style` ... that should fix the tests. This can be manually checked with `make lint`

I reviewed #44 and will merge it, if tests are green.

**Comment by formacube** [comment]
Are you kidding me !!!!
you decide to kill everything after you made me wait for 6 months for you to validate the change of some spaces !!

My code is still plenty of patches since begining of september because you want me to change the formating of the code while it would take you less than 5 minutes to do it.

I have to wait for 6 month ...
and then you decide to kill everything.


Please you first merge my PR, so that I can have some code that works correctly.
Then when you have the time, you implement your new idea.


But in the meantime, at least, I can have a code that work.
