### ISSUE TITLE
Suggestion: showing task description when available on TaskAdmin

### ISSUE THREAD

**Issue by Skrattoune** [boxine/django-huey-monitor#70]
Hi, when going through the `Tasks `admin, I find it pretty difficult to know what the task is about as only the task name is availlable:
![image](https://user-images.githubusercontent.com/56255427/151532237-c6cc19b0-fea9-4f00-abc9-2455b2292d4b.png)
Through this view, we cannot know which task failed (and should trigger a corrective action) and which worked (and can eventually be deleted).

To have an idea about what the tasks are about, we need to edit each task until we find the right one:
![image](https://user-images.githubusercontent.com/56255427/151532053-8e8f3f80-cc26-4166-a6b5-7a1311614fe3.png)
then, first line is the only place where the task description (`desc`) is mentionned.

same with sub-tasks within the changelist view:
![image](https://user-images.githubusercontent.com/56255427/151558789-b19174e8-c69b-4a1e-aab5-9c79fb83efe6.png)

I would suggest to :
1/ display `desc` as the first parameter in list_view
2/ display `desc` as a parameter in change_view (in addition to the current `title`)

I'll be proposing a PR to implement this.

PS: What is your preference? that I continue creating Issues and corresponding PR ? or that I create PR directly, without Issue?

**Comment by Skrattoune** [comment]
Results of PR:
![image](https://user-images.githubusercontent.com/56255427/151558249-dd097fa8-e20a-48ee-bb73-e45bec467a70.png)

![image](https://user-images.githubusercontent.com/56255427/151558366-fdd12ebd-91bc-488b-8c65-5ef0ae37aaef.png)

**Comment by Skrattoune** [comment]
PR: https://github.com/boxine/django-huey-monitor/pull/72
ready for review

**Comment by jedie** [comment]
You PR is merges. Thanks.

**Comment by jedie** [comment]
Released now with v0.4.6
