### ISSUE TITLE
'exception_line': ['This field cannot be blank.']

### ISSUE THREAD

**Issue by mod0** [boxine/django-huey-monitor#81]
Hi,

In SignalInfoModel, `exception_line` field is not nullable, blanks are also not allowed. When storing signals in `store_signals` if `exc = None`, it does not look like `exception_line` will be populated. Consequentially, I see:

```
django.core.exceptions.ValidationError: {'exception_line': ['This field cannot be blank.']}
```

I also noticed that in the TaskModel, field `desc`  (in Huey-Monitor v0.4.6) can't be blank. But the default value for the field is `''` and no value is passed when creating TaskModel in `store_signals`. Consequentially, I see:

```
django.core.exceptions.ValidationError: {'desc': ['This field cannot be blank.']}
```
_Package Versions:_
Python: 3.9
Django: 3.2.2
Huey: 2.4.3
Huey-Monitor: 0.4.6

**Comment by jedie** [comment]
Yes, we should fix this. Any i think we should expand the length of the `desc` field, too.

**Comment by mod0** [comment]
Should I send a PR?
